CREATE TABLE tenants (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tenant_key VARCHAR2(100) UNIQUE NOT NULL, -- external identifier (UUID/slug)

    name VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) DEFAULT 'ACTIVE',

    plan VARCHAR2(50), -- for billing (future use)

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR2(100),

    updated_at TIMESTAMP,
    updated_by VARCHAR2(100),

    is_deleted NUMBER(1) DEFAULT 0,

    version NUMBER DEFAULT 0
);


CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tenant_id NUMBER NOT NULL,

    user_key VARCHAR2(100) UNIQUE NOT NULL, -- external ID

    name VARCHAR2(255),
    email VARCHAR2(255),
    password_hash VARCHAR2(255),

    role VARCHAR2(50),
    status VARCHAR2(50) DEFAULT 'ACTIVE',

    last_login_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR2(100),

    updated_at TIMESTAMP,
    updated_by VARCHAR2(100),

    is_deleted NUMBER(1) DEFAULT 0,

    version NUMBER DEFAULT 0,

    CONSTRAINT fk_users_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants(id),

    CONSTRAINT unique_tenant_email
        UNIQUE (tenant_id, email)
);

CREATE TABLE tickets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ticket_key VARCHAR2(100) UNIQUE NOT NULL, -- external ID

    tenant_id NUMBER NOT NULL,
    created_by_user_id NUMBER NOT NULL,
    assigned_to_user_id NUMBER,

    title VARCHAR2(500) NOT NULL,
    description CLOB,

    status VARCHAR2(50) DEFAULT 'OPEN',
    priority VARCHAR2(50) DEFAULT 'MEDIUM',

    source VARCHAR2(50), -- email, portal, api

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    closed_at TIMESTAMP,

    sla_due_at TIMESTAMP,

    is_deleted NUMBER(1) DEFAULT 0,
    version NUMBER DEFAULT 0,

    CONSTRAINT fk_ticket_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants(id),

    CONSTRAINT fk_ticket_created_by
        FOREIGN KEY (created_by_user_id)
        REFERENCES users(id),

    CONSTRAINT fk_ticket_assigned_to
        FOREIGN KEY (assigned_to_user_id)
        REFERENCES users(id)
);


CREATE TABLE comments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    comment_key VARCHAR2(100) UNIQUE NOT NULL,

    ticket_id NUMBER NOT NULL,
    tenant_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,

    content CLOB NOT NULL,

    is_internal NUMBER(1) DEFAULT 0, -- internal note vs customer reply

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    is_deleted NUMBER(1) DEFAULT 0,
    version NUMBER DEFAULT 0,

    CONSTRAINT fk_comments_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES tickets(id),

    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);


CREATE TABLE attachments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    attachment_key VARCHAR2(100) UNIQUE NOT NULL,

    ticket_id NUMBER NOT NULL,
    tenant_id NUMBER NOT NULL,
    uploaded_by NUMBER NOT NULL,

    file_name VARCHAR2(255),
    file_type VARCHAR2(100),
    file_size NUMBER,

    file_url VARCHAR2(1000), -- stored in S3 / object storage

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    is_deleted NUMBER(1) DEFAULT 0,

    CONSTRAINT fk_attach_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES tickets(id)
);


CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tenant_id NUMBER NOT NULL,

    entity_type VARCHAR2(50), -- TICKET / USER / COMMENT
    entity_id NUMBER,

    action VARCHAR2(50), -- CREATE / UPDATE / DELETE / ASSIGN

    old_value CLOB,
    new_value CLOB,

    performed_by NUMBER,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tickets_partitioned (
    id NUMBER,
    ticket_key VARCHAR2(100),

    tenant_id NUMBER,
    created_at TIMESTAMP,

    status VARCHAR2(50),

    PRIMARY KEY (id)
)
PARTITION BY RANGE (created_at)
(
    PARTITION p_2026 VALUES LESS THAN (TO_DATE('2027-01-01','YYYY-MM-DD')),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);